// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Foundations',
      items: ['foundations/intro'],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [
        'module1/ros2-nodes',
        'module1/ros2-topics',
        'module1/ros2-services',
        'module1/ros2-actions',
        'module1/rclpy',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation',
      items: [
        'module2/urdf-modeling',
        'module2/gazebo-simulation',
        'module2/unity-rendering',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [
        'module3/isaac-sim-basics',
        'module3/isaac-ros',
        'module3/nav2-biped',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      items: [
        'module4/whisper',
        'module4/llm-planning',
        'module4/vla-pipelines',
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: ['capstone/main'],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: ['appendices/hardware-guide', 'appendices/weekly-roadmap'],
    },
  ],
};

export default sidebars;